## Imports

In [3]:
# Basics
import pandas as pd
import numpy as np
import itertools

# Visualization
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import matplotlib.patches as mpatches
from matplotlib.pylab import rcParams
import time

# Warnings
import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)
warnings.filterwarnings('ignore')

## Load Datasets

In [4]:
# load in quarterback fantasy stats data as qb_year
qb_2015 = pd.read_csv('data/season data/2015/2015_QB.csv')
qb_2016 = pd.read_csv('data/season data/2016/2016_QB.csv')
qb_2017 = pd.read_csv('data/season data/2017/2017_QB.csv')
qb_2018 = pd.read_csv('data/season data/2018/2018_QB.csv')
qb_2019 = pd.read_csv('data/season data/2019/2019_QB.csv')
qb_2020 = pd.read_csv('data/season data/2020/2020_QB.csv')
qb_2021 = pd.read_csv('data/season data/2021/2021_QB.csv')
qb_2021.head()

,Rank,Player,CMP,ATT,PCT,YDS,Y/A,TD,INT,SACKS,ATT.1,YDS.1,TD.1,FL,G,FPTS,FPTS/G,ROST
0,1.0,Josh Allen (BUF),409.0,646.0,63.3,"4,407",6.8,36.0,15.0,26.0,122.0,763.0,6.0,3.0,17.0,417.7,24.6,100.0%
1,2.0,Justin Herbert (LAC),443.0,672.0,65.9,"5,014",7.5,38.0,15.0,31.0,63.0,302.0,3.0,1.0,17.0,395.6,23.3,99.9%
2,3.0,Tom Brady (TB),485.0,719.0,67.5,"5,316",7.4,43.0,12.0,22.0,28.0,81.0,2.0,3.0,17.0,386.7,22.7,95.5%
3,4.0,Patrick Mahomes II (KC),436.0,658.0,66.3,"4,828",7.3,37.0,13.0,28.0,66.0,381.0,2.0,4.0,17.0,374.2,22.0,100.0%
4,5.0,Matthew Stafford (LAR),404.0,601.0,67.2,"4,886",8.1,41.0,17.0,30.0,32.0,43.0,0.0,2.0,17.0,346.8,20.4,92.4%

In [5]:
# load in running back fantasy stats data as rb_year
rb_2015 = pd.read_csv('data/season data/2015/2015_RB.csv')
rb_2016 = pd.read_csv('data/season data/2016/2016_RB.csv')
rb_2017 = pd.read_csv('data/season data/2017/2017_RB.csv')
rb_2018 = pd.read_csv('data/season data/2018/2018_RB.csv')
rb_2019 = pd.read_csv('data/season data/2019/2019_RB.csv')
rb_2020 = pd.read_csv('data/season data/2020/2020_RB.csv')
rb_2021 = pd.read_csv('data/season data/2021/2021_RB.csv')
rb_2021.head()

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,YDS.1,Y/R,TD.1,FL,G,FPTS,FPTS/G,ROST
0,1.0,Jonathan Taylor (IND),332.0,"1,811",5.5,83.0,30.0,18.0,40.0,51.0,360.0,9.0,2.0,2.0,17.0,373.1,21.9,100.0%
1,2.0,Austin Ekeler (LAC),206.0,911,4.4,28.0,3.0,12.0,70.0,94.0,647.0,9.2,8.0,3.0,16.0,343.8,21.5,100.0%
2,3.0,Najee Harris (PIT),307.0,"1,200",3.9,37.0,8.0,7.0,74.0,94.0,467.0,6.3,3.0,0.0,17.0,300.7,17.7,99.9%
3,4.0,Joe Mixon (CIN),292.0,"1,205",4.1,32.0,7.0,13.0,42.0,48.0,314.0,7.5,3.0,1.0,16.0,287.9,18.0,100.0%
4,5.0,James Conner (ARI),202.0,752,3.7,35.0,4.0,15.0,37.0,39.0,375.0,10.1,3.0,0.0,15.0,257.7,17.2,99.1%

In [6]:
# load in wide receiver fantasy stats data as wr_year
wr_2015 = pd.read_csv('data/season data/2015/2015_WR.csv')
wr_2016 = pd.read_csv('data/season data/2016/2016_WR.csv')
wr_2017 = pd.read_csv('data/season data/2017/2017_WR.csv')
wr_2018 = pd.read_csv('data/season data/2018/2018_WR.csv')
wr_2019 = pd.read_csv('data/season data/2019/2019_WR.csv')
wr_2020 = pd.read_csv('data/season data/2020/2020_WR.csv')
wr_2021 = pd.read_csv('data/season data/2021/2021_WR.csv')
wr_2021.head()

,Rank,Player,REC,TGT,YDS,Y/R,LG,20+,TD,ATT,YDS.1,TD.1,FL,G,FPTS,FPTS/G,ROST
0,1.0,Cooper Kupp (LAR),145.0,191.0,"1,947",13.4,59.0,57.0,16.0,4.0,18.0,0.0,0.0,17.0,439.5,25.9,100.0%
1,2.0,Davante Adams (LV),123.0,169.0,"1,553",12.6,59.0,37.0,11.0,0.0,0.0,0.0,0.0,16.0,344.3,21.5,100.0%
2,3.0,Deebo Samuel (SF),77.0,121.0,"1,405",18.2,83.0,53.0,6.0,59.0,365.0,8.0,2.0,16.0,339.0,21.2,100.0%
3,4.0,Justin Jefferson (MIN),108.0,167.0,"1,616",15.0,56.0,45.0,10.0,6.0,14.0,0.0,1.0,17.0,330.4,19.4,100.0%
4,5.0,Ja'Marr Chase (CIN),81.0,128.0,"1,455",18.0,82.0,49.0,13.0,7.0,21.0,0.0,1.0,17.0,304.6,17.9,100.0%

In [7]:
# load in tight end fantasy stats data as te_year
te_2015 = pd.read_csv('data/season data/2015/2015_te.csv')
te_2016 = pd.read_csv('data/season data/2016/2016_te.csv')
te_2017 = pd.read_csv('data/season data/2017/2017_te.csv')
te_2018 = pd.read_csv('data/season data/2018/2018_te.csv')
te_2019 = pd.read_csv('data/season data/2019/2019_te.csv')
te_2020 = pd.read_csv('data/season data/2020/2020_te.csv')
te_2021 = pd.read_csv('data/season data/2021/2021_te.csv')
te_2021.head()

,Rank,Player,REC,TGT,YDS,Y/R,LG,20+,TD,ATT,YDS.1,TD.1,FL,G,FPTS,FPTS/G,ROST
0,1.0,Mark Andrews (BAL),107.0,153.0,"1,361",12.7,43.0,27.0,9.0,1.0,0.0,0.0,0.0,17.0,301.1,17.7,100.0%
1,2.0,Travis Kelce (KC),92.0,134.0,"1,125",12.2,69.0,20.0,9.0,2.0,3.0,1.0,1.0,16.0,262.8,16.4,100.0%
2,3.0,Dalton Schultz (DAL),78.0,104.0,808,10.4,32.0,8.0,8.0,0.0,0.0,0.0,0.0,17.0,208.8,12.3,90.6%
3,4.0,George Kittle (SF),71.0,94.0,910,12.8,48.0,17.0,6.0,3.0,20.0,0.0,1.0,14.0,198.0,14.1,98.7%
4,5.0,Zach Ertz (ARI),74.0,112.0,763,10.3,47.0,9.0,5.0,1.0,4.0,0.0,0.0,17.0,180.7,10.6,92.9%

In [79]:
# load in tight end fantasy stats data as k_year
k_2015 = pd.read_csv('data/season data/2015/2015_k.csv')
k_2016 = pd.read_csv('data/season data/2016/2016_k.csv')
k_2017 = pd.read_csv('data/season data/2017/2017_k.csv')
k_2018 = pd.read_csv('data/season data/2018/2018_k.csv')
k_2019 = pd.read_csv('data/season data/2019/2019_k.csv')
k_2020 = pd.read_csv('data/season data/2020/2020_k.csv')
k_2021 = pd.read_csv('data/season data/2021/2021_k.csv')
k_2021.head()

,Rank,Player,FG,FGA,PCT,LG,1-19,20-29,30-39,40-49,50+,XPT,XPA,G,FPTS,FPTS/G,ROST
0,1.0,Daniel Carlson (LV),40.0,43.0,93.0,56.0,0.0,10.0,12.0,12.0,6.0,30.0,33.0,17.0,174.0,10.2,96.5%
1,2.0,Nick Folk (NE),36.0,39.0,92.3,53.0,0.0,9.0,11.0,11.0,5.0,42.0,47.0,17.0,171.0,10.1,51.8%
2,3.0,Justin Tucker (BAL),35.0,37.0,94.6,66.0,0.0,7.0,9.0,13.0,6.0,32.0,32.0,17.0,162.0,9.5,99.8%
3,4.0,Chris Boswell (PIT),36.0,40.0,90.0,56.0,0.0,9.0,8.0,11.0,8.0,27.0,29.0,17.0,162.0,9.5,17.7%
4,5.0,Matt Gay (LAR),32.0,34.0,94.1,55.0,0.0,6.0,15.0,7.0,4.0,48.0,49.0,17.0,159.0,9.4,96.7%

In [80]:
# load in tight end fantasy stats data as dst_year
dst_2015 = pd.read_csv('data/season data/2015/2015_dst.csv')
dst_2016 = pd.read_csv('data/season data/2016/2016_dst.csv')
dst_2017 = pd.read_csv('data/season data/2017/2017_dst.csv')
dst_2018 = pd.read_csv('data/season data/2018/2018_dst.csv')
dst_2019 = pd.read_csv('data/season data/2019/2019_dst.csv')
dst_2020 = pd.read_csv('data/season data/2020/2020_dst.csv')
dst_2021 = pd.read_csv('data/season data/2021/2021_dst.csv')
dst_2021.head()

,Rank,Player,SACK,INT,FR,FF,DEF TD,SFTY,SPC TD,G,FPTS,FPTS/G,ROST
0,1.0,Dallas Cowboys (DAL),41.0,26.0,8.0,13.0,6.0,0.0,3.0,17.0,185.0,10.9,74.0%
1,2.0,New England Patriots (NE),36.0,23.0,7.0,11.0,3.0,0.0,0.0,17.0,158.0,9.3,38.0%
2,3.0,Miami Dolphins (MIA),48.0,14.0,13.0,14.0,5.0,0.0,1.0,17.0,155.0,9.1,20.9%
3,4.0,Buffalo Bills (BUF),42.0,19.0,11.0,10.0,1.0,0.0,0.0,17.0,151.0,8.9,99.5%
4,5.0,New Orleans Saints (NO),46.0,18.0,7.0,12.0,2.0,0.0,0.0,17.0,145.0,8.5,89.3%

## Clean DFs

In [84]:
# Function to drop columns based on position and strip team name from player column
def clean_df(df, position):
    if position == 'Quarterback':
        to_drop = ['CMP', 'ATT', 'PCT', 'YDS', 'Y/A', 'TD', 'INT', 'SACKS', 'ATT.1', 'YDS.1', 'TD.1', 'FL', 
                   'G', 'FPTS/G', 'ROST']
        
    elif position == 'Running Back':
        to_drop = ['ATT', 'YDS', 'Y/A', 'LG', '20+', 'TD', 'REC', 'TGT', 'Y/R', 'YDS.1', 'TD.1', 'FL', 
                   'G', 'FPTS/G', 'ROST']
        
    elif position == 'Wide Receiver':
        to_drop = ['REC', 'TGT', 'YDS', 'Y/R', 'LG', '20+', 'TD', 'ATT', 'YDS.1', 'TD.1', 'FL', 
                   'G', 'FPTS/G', 'ROST']
        
    elif position == 'Tight End':
        to_drop = ['REC', 'TGT', 'YDS', 'LG', '20+', 'Y/R', 'TD', 'ATT', 'YDS.1', 'TD.1', 'FL', 
                   'G', 'FPTS/G', 'ROST']
        
    elif position == 'Kicker':
        to_drop = ['FG', 'FGA', 'PCT', 'LG', '1-19', '20-29', '30-39', '40-49', '50+', 'XPT', 'XPA', 'G', 'FPTS/G', 'ROST']
        
    elif position == 'Defense':
        to_drop = ['SACK', 'INT', 'FR', 'FF', 'DEF TD', 'SFTY', 'SPC TD', 'G', 'FPTS/G', 'ROST']

    # Drop columns
    df = df.drop(to_drop, axis=1).dropna()
    
    # Remove team name in parenthesis from player
    df['Player'] = df['Player'].str.split('(').str.get(0)
    df['Player'] = df['Player'].astype(str).str.strip()
    
    return df

In [17]:
# Clean quarterback dfs
qb_2015_pts = clean_df(qb_2015, 'Quarterback')
qb_2016_pts = clean_df(qb_2016, 'Quarterback')
qb_2017_pts = clean_df(qb_2017, 'Quarterback')
qb_2018_pts = clean_df(qb_2018, 'Quarterback')
qb_2019_pts = clean_df(qb_2019, 'Quarterback')
qb_2020_pts = clean_df(qb_2020, 'Quarterback')
qb_2021_pts = clean_df(qb_2021, 'Quarterback')

qb_2015_pts

    Rank           Player   FPTS
0    1.0       Cam Newton  389.1
1    2.0        Tom Brady  344.7
2    3.0   Russell Wilson  336.3
3    4.0    Blake Bortles  316.1
4    5.0    Carson Palmer  309.2
..   ...              ...    ...
70  71.0     Joe Webb III   -0.1
71  72.0    Scott Tolzien   -0.1
72  73.0  Jimmy Garoppolo   -0.3
73  74.0     Drew Stanton   -1.1
74  75.0     Sean Renfree   -2.0

[75 rows x 3 columns]

In [18]:
# Clean running back dfs
rb_2015_pts = clean_df(rb_2015, 'Running Back')
rb_2016_pts = clean_df(rb_2016, 'Running Back')
rb_2017_pts = clean_df(rb_2017, 'Running Back')
rb_2018_pts = clean_df(rb_2018, 'Running Back')
rb_2019_pts = clean_df(rb_2019, 'Running Back')
rb_2020_pts = clean_df(rb_2020, 'Running Back')
rb_2021_pts = clean_df(rb_2021, 'Running Back')
rb_2021_pts

      Rank           Player   FPTS
0      1.0  Jonathan Taylor  373.1
1      2.0    Austin Ekeler  343.8
2      3.0     Najee Harris  300.7
3      4.0        Joe Mixon  287.9
4      5.0     James Conner  257.7
..     ...              ...    ...
192  193.0   Jordan Wilkins    0.0
193  194.0   Elijah McGuire    0.0
194  195.0    Kenjon Barner    0.0
195  196.0     Nate McCrary   -0.1
196  197.0   Trenton Cannon   -1.6

[197 rows x 3 columns]

In [19]:
# Clean wide receiver dfs
wr_2015_pts = clean_df(wr_2015, 'Wide Receiver')
wr_2016_pts = clean_df(wr_2016, 'Wide Receiver')
wr_2017_pts = clean_df(wr_2017, 'Wide Receiver')
wr_2018_pts = clean_df(wr_2018, 'Wide Receiver')
wr_2019_pts = clean_df(wr_2019, 'Wide Receiver')
wr_2020_pts = clean_df(wr_2020, 'Wide Receiver')
wr_2021_pts = clean_df(wr_2021, 'Wide Receiver')
wr_2021_pts

      Rank            Player   FPTS
0      1.0       Cooper Kupp  439.5
1      2.0     Davante Adams  344.3
2      3.0      Deebo Samuel  339.0
3      4.0  Justin Jefferson  330.4
4      5.0     Ja'Marr Chase  304.6
..     ...               ...    ...
262  263.0       Devin Smith    0.0
263  264.0      Alex Bachman   -0.3
264  265.0        J.J. Koski   -2.0
265  266.0   Travis Benjamin   -2.0
266  267.0   Diontae Spencer   -3.3

[267 rows x 3 columns]

In [20]:
# Clean tight ends dfs
te_2015_pts = clean_df(te_2015, 'Tight End')
te_2016_pts = clean_df(te_2016, 'Tight End')
te_2017_pts = clean_df(te_2017, 'Tight End')
te_2018_pts = clean_df(te_2018, 'Tight End')
te_2019_pts = clean_df(te_2019, 'Tight End')
te_2020_pts = clean_df(te_2020, 'Tight End')
te_2021_pts = clean_df(te_2021, 'Tight End')
te_2021_pts

      Rank            Player   FPTS
0      1.0      Mark Andrews  301.1
1      2.0      Travis Kelce  262.8
2      3.0    Dalton Schultz  208.8
3      4.0     George Kittle  198.0
4      5.0         Zach Ertz  180.7
..     ...               ...    ...
141  142.0  James Winchester    0.0
142  143.0    Patrick Scales    0.0
143  144.0    Andrew DePaola    0.0
144  145.0    Colin Thompson    0.0
145  146.0       Taysom Hill    0.0

[146 rows x 3 columns]

In [86]:
# Clean kickers dfs
k_2015_pts = clean_df(k_2015, 'Kicker')
k_2016_pts = clean_df(k_2016, 'Kicker')
k_2017_pts = clean_df(k_2017, 'Kicker')
k_2018_pts = clean_df(k_2018, 'Kicker')
k_2019_pts = clean_df(k_2019, 'Kicker')
k_2020_pts = clean_df(k_2020, 'Kicker')
k_2021_pts = clean_df(k_2021, 'Kicker')
k_2021_pts.head()

   Rank          Player   FPTS
0   1.0  Daniel Carlson  174.0
1   2.0       Nick Folk  171.0
2   3.0   Justin Tucker  162.0
3   4.0   Chris Boswell  162.0
4   5.0        Matt Gay  159.0

In [87]:
# Clean defense dfs
dst_2015_pts = clean_df(dst_2015, 'Defense')
dst_2016_pts = clean_df(dst_2016, 'Defense')
dst_2017_pts = clean_df(dst_2017, 'Defense')
dst_2018_pts = clean_df(dst_2018, 'Defense')
dst_2019_pts = clean_df(dst_2019, 'Defense')
dst_2020_pts = clean_df(dst_2020, 'Defense')
dst_2021_pts = clean_df(dst_2021, 'Defense')
dst_2021_pts

    Rank                 Player   FPTS
0    1.0         Dallas Cowboys  185.0
1    2.0   New England Patriots  158.0
2    3.0         Miami Dolphins  155.0
3    4.0          Buffalo Bills  151.0
4    5.0     New Orleans Saints  145.0
5    6.0   Tampa Bay Buccaneers  141.0
6    7.0     Indianapolis Colts  138.0
7    8.0     Kansas City Chiefs  131.0
8    9.0      Arizona Cardinals  126.0
9   10.0      Minnesota Vikings  124.0
10  11.0       Tennessee Titans  123.0
11  12.0       Los Angeles Rams  121.0
12  13.0         Denver Broncos  119.0
13  14.0    San Francisco 49ers  118.0
14  15.0      Green Bay Packers  117.0
15  16.0    Philadelphia Eagles  111.0
16  17.0    Pittsburgh Steelers  111.0
17  18.0     Cincinnati Bengals  108.0
18  19.0          Chicago Bears  105.0
19  20.0       Cleveland Browns  104.0
20  21.0       Seattle Seahawks   95.0
21  22.0  Washington Commanders   92.0
22  23.0      Carolina Panthers   89.0
23  24.0         Houston Texans   87.0
24  25.0        New York Giants   86.0
25  26.0       Baltimore Ravens   85.0
26  27.0   Los Angeles Chargers   78.0
27  28.0      Las Vegas Raiders   65.0
28  29.0        Atlanta Falcons   65.0
29  30.0   Jacksonville Jaguars   64.0
30  31.0          New York Jets   58.0
31  32.0          Detroit Lions   58.0

## Concat DFs

In [88]:
# Make list of position dfs for each year
df_2015_list = [qb_2015_pts, rb_2015_pts, wr_2015_pts, te_2015_pts, k_2015_pts, dst_2015_pts]
df_2016_list = [qb_2016_pts, rb_2016_pts, wr_2016_pts, te_2016_pts, k_2016_pts, dst_2016_pts]
df_2017_list = [qb_2017_pts, rb_2017_pts, wr_2017_pts, te_2017_pts, k_2017_pts, dst_2017_pts]
df_2018_list = [qb_2018_pts, rb_2018_pts, wr_2018_pts, te_2018_pts, k_2018_pts, dst_2018_pts]
df_2019_list = [qb_2019_pts, rb_2019_pts, wr_2019_pts, te_2019_pts, k_2019_pts, dst_2019_pts]
df_2020_list = [qb_2020_pts, rb_2020_pts, wr_2020_pts, te_2020_pts, k_2020_pts, dst_2020_pts]
df_2021_list = [qb_2021_pts, rb_2021_pts, wr_2021_pts, te_2021_pts, k_2021_pts, dst_2021_pts]

In [89]:
# Concatenate dfs for all positions
df_2015 = pd.concat(df_2015_list, axis=0, ignore_index=True)    
df_2016 = pd.concat(df_2016_list, axis=0, ignore_index=True)
df_2017 = pd.concat(df_2017_list, axis=0, ignore_index=True) 
df_2018 = pd.concat(df_2018_list, axis=0, ignore_index=True) 
df_2019 = pd.concat(df_2019_list, axis=0, ignore_index=True) 
df_2020 = pd.concat(df_2020_list, axis=0, ignore_index=True) 
df_2021 = pd.concat(df_2021_list, axis=0, ignore_index=True) 
df_2021

     Rank                Player   FPTS
0     1.0            Josh Allen  417.7
1     2.0        Justin Herbert  395.6
2     3.0             Tom Brady  386.7
3     4.0    Patrick Mahomes II  374.2
4     5.0      Matthew Stafford  346.8
..    ...                   ...    ...
772  28.0     Las Vegas Raiders   65.0
773  29.0       Atlanta Falcons   65.0
774  30.0  Jacksonville Jaguars   64.0
775  31.0         New York Jets   58.0
776  32.0         Detroit Lions   58.0

[777 rows x 3 columns]

## Load ADP Datasets

In [106]:
# load in adp data as adp_year
adp_2015 = pd.read_csv('data/adp/FantasyPros_2015_Overall_ADP_Rankings.csv')
adp_2016 = pd.read_csv('data/adp/FantasyPros_2016_Overall_ADP_Rankings.csv')
adp_2017 = pd.read_csv('data/adp/FantasyPros_2017_Overall_ADP_Rankings.csv')
adp_2018 = pd.read_csv('data/adp/FantasyPros_2018_Overall_ADP_Rankings.csv')
adp_2019 = pd.read_csv('data/adp/FantasyPros_2019_Overall_ADP_Rankings.csv')
adp_2020 = pd.read_csv('data/adp/FantasyPros_2020_Overall_ADP_Rankings.csv')
adp_2021 = pd.read_csv('data/adp/FantasyPros_2021_Overall_ADP_Rankings.csv')
adp_2021.head()

,Rank,Player,Team,Bye,POS,ESPN,RTSports,MFL,Fantrax,FFC,Sleeper,AVG
0,1.0,Christian McCaffrey,CAR,13,RB1,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,2.0,Dalvin Cook,MIN,7,RB2,2.0,2.0,2.0,2.0,2.0,2.0,2.0
2,3.0,Alvin Kamara,NO,6,RB3,3.0,3.0,3.0,3.0,3.0,3.0,3.0
3,4.0,Derrick Henry,TEN,13,RB4,4.0,4.0,4.0,4.0,4.0,4.0,4.0
4,5.0,Ezekiel Elliott,DAL,7,RB5,8.0,5.0,6.0,5.0,5.0,5.0,5.8

## Clean ADP Datasets

In [107]:
def clean_adp(df):

    # Rename rank column to ADP
    df['ADP'] = df['Rank']
    
    #Columns to drop
    to_drop = ['Rank', 'Bye', 'Team', 'ESPN', 'RTSports', 'MFL', 'Fantrax', 'FFC', 'Sleeper', 'AVG']

    # Drop columns and keep top 100 adp
    df = df.drop(to_drop, axis=1).dropna().head(100)
    
    # Remove team name in parenthesis from player
    df['POS'] = df['POS'].str.replace('\d+', '')
    
    return df

In [108]:
# Run function to clean adp_dfs
adp_2015_100 = clean_adp(adp_2015)
adp_2016_100 = clean_adp(adp_2016)
adp_2017_100 = clean_adp(adp_2017)
adp_2018_100 = clean_adp(adp_2018)
adp_2019_100 = clean_adp(adp_2019)
adp_2020_100 = clean_adp(adp_2020)
adp_2021_100 = clean_adp(adp_2021)
adp_2021_100

                  Player  POS    ADP
0    Christian McCaffrey   RB    1.0
1            Dalvin Cook   RB    2.0
2           Alvin Kamara   RB    3.0
3          Derrick Henry   RB    4.0
4        Ezekiel Elliott   RB    5.0
..                   ...  ...    ...
95        Dallas Goedert   TE   96.0
96          James Conner   RB   97.0
97        D.J. Chark Jr.   WR   98.0
98         Jarvis Landry   WR   99.0
99  Tampa Bay Buccaneers  DST  100.0

[100 rows x 3 columns]

### Clean ADP Datasets for Kickers and Defense

In [109]:
def clean_adp_k(df):

    # Rename rank column to ADP
    df['ADP'] = df['Rank']
    
    #Columns to drop
    to_drop = ['Rank', 'Bye', 'Team', 'ESPN', 'RTSports', 'MFL', 'Fantrax', 'FFC', 'Sleeper', 'AVG']

    # Drop columns and keep top 100 adp
    df = df.drop(to_drop, axis=1).dropna().head(200)
    
    # Remove team name in parenthesis from player
    df['POS'] = df['POS'].str.replace('\d+', '')
    
    return df

In [110]:
# Run function to clean adp_dfs
adp_2015_k = clean_adp_k(adp_2015)
adp_2016_k = clean_adp_k(adp_2016)
adp_2017_k = clean_adp_k(adp_2017)
adp_2018_k = clean_adp_k(adp_2018)
adp_2019_k = clean_adp_k(adp_2019)
adp_2020_k = clean_adp_k(adp_2020)
adp_2021_k = clean_adp_k(adp_2021)
adp_2021_k

                  Player  POS    ADP
0    Christian McCaffrey   RB    1.0
1            Dalvin Cook   RB    2.0
2           Alvin Kamara   RB    3.0
3          Derrick Henry   RB    4.0
4        Ezekiel Elliott   RB    5.0
..                   ...  ...    ...
195         Randall Cobb   WR  196.0
196           Gabe Davis   WR  197.0
197          Matt Prater    K  198.0
198         Daniel Jones   QB  199.0
199    Green Bay Packers  DST  200.0

[200 rows x 3 columns]

## Merge ADP and Rank Datasets

In [111]:
#Merge ADP and Rank data for each player in top 100 ADP
adp_2015_df = pd.merge(adp_2015_100, df_2015, how = 'left', on='Player').fillna(0)
adp_2016_df = pd.merge(adp_2016_100, df_2016, how = 'left', on='Player').fillna(0)
adp_2017_df = pd.merge(adp_2017_100, df_2017, how = 'left', on='Player').fillna(0)
adp_2018_df = pd.merge(adp_2018_100, df_2018, how = 'left', on='Player').fillna(0)
adp_2019_df = pd.merge(adp_2019_100, df_2019, how = 'left', on='Player').fillna(0)
adp_2020_df = pd.merge(adp_2020_100, df_2020, how = 'left', on='Player').fillna(0)
adp_2021_df = pd.merge(adp_2021_100, df_2021, how = 'left', on='Player').fillna(0)
adp_2021_df

                  Player  POS    ADP   Rank   FPTS
0    Christian McCaffrey   RB    1.0   38.0  127.5
1            Dalvin Cook   RB    2.0   16.0  206.3
2           Alvin Kamara   RB    3.0    8.0  234.7
3          Derrick Henry   RB    4.0   22.0  193.3
4        Ezekiel Elliott   RB    5.0    7.0  252.1
..                   ...  ...    ...    ...    ...
95        Dallas Goedert   TE   96.0    8.0  165.0
96          James Conner   RB   97.0    5.0  257.7
97        D.J. Chark Jr.   WR   98.0  136.0   34.4
98         Jarvis Landry   WR   99.0   52.0  133.0
99  Tampa Bay Buccaneers  DST  100.0    6.0  141.0

[100 rows x 5 columns]

### Merge ADP and Rank Datasets for Kickers and Defense

In [112]:
#Merge ADP and Rank data for each player in top 100 ADP
adp_2015_k = pd.merge(adp_2015_k, df_2015, how = 'left', on='Player').fillna(0)
adp_2016_k = pd.merge(adp_2016_k, df_2016, how = 'left', on='Player').fillna(0)
adp_2017_k = pd.merge(adp_2017_k, df_2017, how = 'left', on='Player').fillna(0)
adp_2018_k = pd.merge(adp_2018_k, df_2018, how = 'left', on='Player').fillna(0)
adp_2019_k = pd.merge(adp_2019_k, df_2019, how = 'left', on='Player').fillna(0)
adp_2020_k = pd.merge(adp_2020_k, df_2020, how = 'left', on='Player').fillna(0)
adp_2021_k = pd.merge(adp_2021_k, df_2021, how = 'left', on='Player').fillna(0)
adp_2021_k

                  Player  POS    ADP  Rank   FPTS
0    Christian McCaffrey   RB    1.0  38.0  127.5
1            Dalvin Cook   RB    2.0  16.0  206.3
2           Alvin Kamara   RB    3.0   8.0  234.7
3          Derrick Henry   RB    4.0  22.0  193.3
4        Ezekiel Elliott   RB    5.0   7.0  252.1
..                   ...  ...    ...   ...    ...
195         Randall Cobb   WR  196.0  75.0   93.6
196           Gabe Davis   WR  197.0  58.0  125.9
197          Matt Prater    K  198.0   7.0  154.0
198         Daniel Jones   QB  199.0  27.0  174.6
199    Green Bay Packers  DST  200.0  15.0  117.0

[200 rows x 5 columns]

## Export Final Datasets

In [113]:
adp_2015_df.to_csv('data/adp_2015.csv')
adp_2016_df.to_csv('data/adp_2016.csv')
adp_2017_df.to_csv('data/adp_2017.csv')
adp_2018_df.to_csv('data/adp_2018.csv')
adp_2019_df.to_csv('data/adp_2019.csv')
adp_2020_df.to_csv('data/adp_2020.csv')
adp_2021_df.to_csv('data/adp_2021.csv')

### Export Final Datasets for Kickers and Defense

In [114]:
adp_2015_k.to_csv('data/adp_2015_k.csv')
adp_2016_k.to_csv('data/adp_2016_k.csv')
adp_2017_k.to_csv('data/adp_2017_k.csv')
adp_2018_k.to_csv('data/adp_2018_k.csv')
adp_2019_k.to_csv('data/adp_2019_k.csv')
adp_2020_k.to_csv('data/adp_2020_k.csv')
adp_2021_k.to_csv('data/adp_2021_k.csv')